import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Toastercontext from './context/Toastercontext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>

        <Toastercontext />
        {children}</body>
    </html>
  )
}
